parameters:
  load_dataset_id: newsletter-summerizer-agent-task
  summarization_agent_model_id: gpt-4o-mini
  summarization_agent_mock: false
  summarization_max_characters: 256
  val_split_ratio: 0.1
  test_split_ratio: 0.1
  min_document_characters: 50
  min_quality_score: 0.3
  augmentation_loops: 4
  max_workers: 4
  data_dir: data/
